## For developer only
## Please read use guide in ./docs/dev-on-docker-env-note.pdf
## [usage]
## Run in development env
#     docker-compose up
## To see config after merge please run command:
#     docker-compose config
version: "3.7"
services:
  petline_app:
    working_dir: /var/www/html/PetLine/BE
    user: "$uid"
    image: petline-php-fpm-dev
    build:
      target: php-fpm-dev
      args:
        USER_ID: ${uid:-1000}
        GROUP_ID: ${gid:-1000}
    volumes:
      - ./BE:/var/www/html/PetLine/BE:delegated
      - ./BE/.docker/php/conf.d/z-xdebug.dev.ini:/usr/local/etc/php/conf.d/z-xdebug.dev.ini
      - ./BE/.docker/php/conf.d/z-php.dev.ini:/usr/local/etc/php/conf.d/z-php.dev.ini
    extra_hosts: #uncomment this section if you use linux and want run xdebug
      - host.docker.internal:host-gateway # support on linux host, container communicate with host over domain host.docker.internal (docker engine ver > 20.10)
    environment:
      APPLICATION_ENV: development
      # xdebug
      PHP_IDE_CONFIG: serverName=petline-docker
      # for run phpunit only, see environment var needed in tests/bootstrap.php (search with keyword 'getenv')
      APP_SUBDOMAIN: localhost
      TEST_DB_HOST: petline_db
      TEST_DB_NAME: petline_unittest

  petline_public:
    working_dir: /var/www/html/PetLine/BE/public
    image: petline-nginx-builder
    build:
      target: nginx-builder
    volumes:
      - ./BE/public:/var/www/html/PetLine/BE/public
      - ./BE/storage/app/public:/var/www/html/PetLine/BE/storage/app/public
      - ./BE/.docker/nginx/conf.d/petline-app.conf:/etc/nginx/conf.d/default.conf
      - ./BE/.docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  petline_fe:
    working_dir: /var/www/html/PetLine/FE
    user: "$uid"
    image: petline-fe-dev
    build:
      context: ./FE
      dockerfile: Dockerfile
      target: petline-fe
      args:
        USER_ID: ${uid:-1000}
        GROUP_ID: ${gid:-1000}
        GIT_COMMIT_HASH: N/A
        GIT_BRANCH_NAME: N/A
    volumes:
      - ./FE:/var/www/html/PetLine/FE
    ports:
      - 4200:4200
    environment:
      NG_HOST: 0.0.0.0
      NG_PORT: 4200

  petline_db:
    container_name: petline_db
    image: mysql:8.0.28
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
        "--skip-name-resolve",
        "--sql-mode=",
        "--group_concat_max_len=100000",
        "--slow_query_log=1",
        "--long_query_time=1",
        "--slow_query_log_file=/var/log/mysql/slow.log",
        "--log_queries_not_using_indexes=0",
        "--general-log=1",
        "--log-output=TABLE",
        "--local-infile=1",
      ]
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: huypq29102001
      MYSQL_DATABASE: petline
      TZ: Asia/Tokyo
    volumes:
      - data-mysql-petline:/var/lib/mysql:delegated

  session_storage:
    container_name: session_storage_petline
    image: redis:6.2.5-alpine3.14
    restart: always

# [ volumes definition ]
# creates Docker volumes which can be mounted by other containers too e.g. for backup
volumes:
  data-mysql-petline:
    driver: local
